### ISSUE TITLE
Images missing from items in the JSON data

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/research#3]
The code team needs help to figure out whether or not these pieces are being displayed in the building and to take photos of the pieces. A large portion of the items that are missing were not shown on the map created by the research team. If the pieces are being displayed in the building the code team will need images of the missing pieces. I have a camera that the team can borrow if need be.

No Images
Map IDs: ?? - Diptych VIII, 4/10 - Linda Finnell - JSON ID: 14
Map IDs: ?? - Western Speech Vol J - Nate Glaspie - JSON ID: 19
Map IDs: ?? - Untitled - Jose Enrique Krap - JSON ID: 23
Map IDs: ?? - Wish! Angel - Gregory Metz - JSON ID: 29
Map IDs: ?? - Untitled - John Pomara  - JSON ID: 34
Map IDs: ?? - Letting You Go - Jason Singleton - JSON ID: 39
Map IDs: ?? - Celebrate - Jaune Smith - JSON ID: 40
Map IDs: ?? - Lubbock Housing Project 1 - David Willburn - JSON ID: 44
Map IDs: 19 - Surprised Man - Hiram Williams - JSON ID:  47
Map IDs: 23 - Untitled - Hart - 23 - JSON ID: 66
Map IDs: 15 - Untitled - Otis Jones - JSON ID: 69
Map IDs: 11 - After an Interval II - Chris Powell - JSON ID: 76
Map IDs: ?? - Untitled - Ludwig Schwarz - JSON ID: 78
Map IDs: ?? - Last Chair - Paul Slocum - JSON ID: 80

**Comment by shruthiravi15** [comment]
Kelsee and Geoffrey were able to locate all the pieces of artwork except 3: Celebrate (Jaune Smith), Untitled (Ludwog Schwarz), Last Chair (Paul Slocum). The artwork images are uploaded to a separate issue. Other than the three images that have a Map ID, the other pieces are all located in Johnson (JO) so they currently don't have a Map ID due to the fact it's not located in the building. Once updated, we will post accordingly.
